name: ci

on:
    push:
        branches:
            - main
            - staging
            - dev
    pull_request:
        branches:
            - main
            - staging
            - dev

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'

            - name: Install dependencies
              run: npm install

            - name: Build application
              run: npm run build:prod

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Development Docker image
              if: (github.event_name == 'pull_request' && github.base_ref == 'dev') || (github.event_name == 'push' && github.ref == 'refs/heads/dev')
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/trailblazers-api-dev:latest -f docker/dockerfile .
                  docker push ${{ secrets.DOCKER_USERNAME }}/trailblazers-api-dev:latest

            - name: Build and push Production Docker image
              if: (github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'staging')) || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'))
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/trailblazers-api:latest -f docker/dockerfile .
                  docker push ${{ secrets.DOCKER_USERNAME }}/trailblazers-api:latest
